version: '3'
services:
  web:
    image: node
    build: .
    # command: npm run server-dev
    # command: node server/db/mongoDB.js
    ports: 3000:3005
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    command: mongod
    ports: 27017:27017